Adding use-herald-action to pull request tools
sdras/awesome-actions pull request #478
Opened 2020-09-01 21:17 UTC by gagoar

Hi! I wanted to add `user-herald-action` to your awesome list.  We used it plenty at Coursera and I thought it could be useful for other people as well!

2020-09-01 21:20 UTC, gagoar commented on README.md
> +- [Herald rules for Github: Add subscribers, assignees, labels and more to your PR](https://github.com/gagoar/use-herald-action)
```suggestion
- [Herald rules for GitHub: Add subscribers, assignees, labels and more to your PR](https://github.com/gagoar/use-herald-action)
```

2020-09-05 01:27 UTC, sdras requested changes
Please Title-Case as per CONTRIBUTING.md

2020-09-05 02:16 UTC, gagoar commented
done!

2020-09-20 20:59 UTC, sdras approved these changes

2020-09-20 20:59 UTC, merged

2020-09-20 20:59 UTC, sdras commented
Thanks!